name: 'Build and push docker image'
inputs:
  version:
    required: true
    type: string
  tags:
    required: true
    type: string
  labels:
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push images
      uses: docker/build-push-action@v4
      with:
        file: cmd/proxy/Dockerfile
        build-args: VERSION=${{ inputs.version }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        push: true
        platforms: linux/amd64,linux/arm64
