name: release-latest
on:
  push:
    tags:
      - '**'
jobs:
  docker-push-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            gomods/athens
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest

      - name: Build and push latest tag
        uses: ./.github/workflows/build-push-image.yaml
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          version: ${{ github.ref_name }}
