name: Release canary and commit tags
on:
  push:
    branches:
      - main
jobs:
  docker-push-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push canary image
        uses: ./.github/workflows/build-push-image.yaml
        with:
          tags: gomods/athens:canary,gomods/athens-dev:${{ steps.vars.outputs.sha_short }}
          version: ${{ github.sha }}